spring.application.name=broudin-pierce-alerts
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.basic.enabled=false
jacoco-agent.arg=-javaagent:target/jacoco.exec

